server:
  port: 8080

spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://(paste RDS endpoint)
    username: root        # TODO: change to your MySQL username
    password: root        # TODO: change to your MySQL password
=======
    url: jdbc:mysql://insurance-db.ct4268qog34b.ap-south-1.rds.amazonaws.com:3306/insurance_db?useSSL=false&serverTimezone=UTC
    username: admin        # TODO: change to your MySQL username
    password: rootuser        # TODO: change to your MySQL password
>>>>>>> cfd2cc8f6f0d5f27e767b94614075faca417427a

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET"
    expiration-ms: 3600000
